server {
    listen 80;
    server_name localhost;

    # Backend API
    location /rnh/api/ {
        rewrite ^/rnh/api/(.*) /$1 break;
        proxy_pass http://backend:3001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend Socket.io
    location /rnh/socket.io/ {
        proxy_pass http://backend:3001/rnh/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend Next.js (App)
    location /rnh/ {
        proxy_pass http://frontend:3000/rnh/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
