name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: 22022
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # O usar key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ ! -d "/root/rnh-live" ]; then
              cd /root
              git clone https://github.com/santototorres/rnh-live.git
            fi
            
            cd /root/rnh-live
            git pull origin main
            
            # Soporte cruzado para docker-compose (v1) o docker compose (v2)
            if command -v docker-compose &> /dev/null; then
              docker-compose down
              docker-compose up -d --build
            else
              docker compose down
              docker compose up -d --build
            fi
