name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }} # O usar key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Ir a la carpeta raíz por defecto o crearla si no existe (la primera vez fallará el git pull si no está clonado)
            cd /root/rnh-live || (cd /root && git clone https://github.com/santototorres/rnh-live.git && cd rnh-live)
            git pull origin main
            
            # Detener contenedores existentes
            docker-compose down
            
            # Reconstruir y levantar con los nuevos cambios
            docker-compose up -d --build
